[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
verbosity = 5
ffi = true

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
